version: '3.8'

# TO RUN
# docker compose up --build

services:
  frontend:
    build:
      context: ./app-front
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - backend

  backend:
    build:
      context: ./app-server
    ports:
      - "8000:8000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge